### ISSUE TITLE
parse_url() invalid behaviour with UTF-8 on macOS

### ISSUE THREAD

**Issue by abumostafa** [webignition/url#28]
Hello,

I have a problem using the library on macOS with utf-8 characters.

Here is an example

```
$uri = 'http://de.wikipedia.org/wiki/Nattō';
$urlParser = new \webignition\Url\Url($uri);
echo $urlParser->__toString();
```

The output is:
Actual: `http://de.wikipedia.org/wiki/Natt_`
Expected: `http://de.wikipedia.org/wiki/Natt%C5%8D`

Here is an example of [UTF-8 safe parsing ](https://secure.php.net/manual/en/function.parse-url.php#114817)

**Comment by webignition** [comment]
Cool, thanks for the report!

**Comment by webignition** [comment]
Interesting, I'm not getting the quite same results. If I supply a string of 'http://de.wikipedia.org/wiki/Nattō', I'm getting the same back again.

Nevertheless, RFC 3986 is quite specific about what characters can be present in a URL. I'll work on a fix to percent-encode URL paths.

**Comment by webignition** [comment]
Should be all good now in release [2.2](https://github.com/webignition/url/releases/tag/2.2)

**Comment by abumostafa** [comment]
Thanks a lot

**Comment by abumostafa** [comment]
I have tested your solution however it did not work :( the problem is [here](https://github.com/webignition/url/blob/master/src/Url/Parser.php#L61) in `parse_url`
When you call parse URL it returns wrong value

**Comment by webignition** [comment]
Seems to be working as far as I can tell based on the example you initially provided:

```php
$url = new \webignition\Url\Url('http://de.wikipedia.org/wiki/Nattō');
var_dump((string)$url);
// http://de.wikipedia.org/wiki/Natt%C5%8D
```
That values returned by `parse_url` are not ultimately correct is not a concern as there is code that subsequently remedies the matter of otherwise-incorrect path encoding.

What gives you the impression that there is still an issue? Can you give me another example of what you expect vs what you get?

**Comment by webignition** [comment]
Maybe your terminal is not able to render the relevant characters? I'm not able to find any substantiated issues with PHP itself to suggest that `parse_url` behaves incorrectly under macos.

Have you run the tests that come with this package?

**Comment by webignition** [comment]
Looks like there is indeed a [possible issue with `parse_url()` under OS X/mac OS](https://bugs.php.net/bug.php?id=52923). I say 'possible' as whether the matter constitutes a bug is somewhat open to interpretation. I'm not going to weigh in here as to whether the matter is or isn't a bug, that's up to the PHP maintainers to determine. There's not really anything I can do about that.

From looking at the above bug report, it seems like `parse_url()` was never intended to be multibyte-aware and that unreserved characters should be percent-encoded. By definition, `http://de.wikipedia.org/wiki/Nattō` is not valid by means of it containing unreserved characters that are not percent-encoded.

Implementing a change to handle unreserved unicode characters in a URL string brings along assumptions regarding the state of encoding of the URL being parsed. I'm not happy with such assumptions, and I'm not happy implementing and then maintaining a means for handling technically invalid URL strings.

If you correctly encode the URL to be parsed you'll not have any problems.

**Comment by abumostafa** [comment]
I totally agree with you the problem is `parse_url` is not multi-byte aware. and the problem seems to be platform and encoding specific. 
When i changed the OS `locale` to `C` instead of `en_US.UTF-8` everything seems to work pretty much fine. So i would not bother about it anymore.

Thanks for taking the time to help and to support.

Feel free to close this issue
