### ISSUE TITLE
always return webignition\Url\Query\Query from getQuery()

### ISSUE THREAD

**Issue by ceejayoz** [webignition/url#8]
`getQuery()` should return a `webignition\Url\Query\Query` at all times, even if there is no query string on the URL. This would greatly simplify adding query string parameters to a URL when that URL may or may not have one already.

This should work:

```
$url = new \webignition\Url\Url('http://example.com/');
$url->getQuery()->add('key', 'value');
```

**Comment by webignition** [comment]
Fixed in PR https://github.com/webignition/url/pull/11.

Will be in upcoming release 1.9.15.

**Comment by webignition** [comment]
Now in https://github.com/webignition/url/releases/tag/1.9.15
